### ISSUE TITLE
Indentation with spaces

### ISSUE THREAD

**Issue by svenkeidel** [svenkeidel/hug#12]
@vajkonny, I think we should discuss issues in English s.t. non-native German speakers can follow the  discussion.

I reviewed your changes and saw that you used tabs for indentation. Normally I'm not that strict about that stuff, but in the case of Haskell, indentation really affects the semantic of the code. Even GHC complains about the tabs. So I went ahead and reformatted the tests with 2 spaces per block of indentations.

Also, I tried to bring the tests into a compiling state, by adding function stubs that are implemented with `undefined`. Can you help me fix the compile errors, than we have an easier job in the next meeting.

Best,
Sven

**Comment by vajkonny** [comment]
Am 27.09.2015 10:53, schrieb Sven Keidel:

> @vajkonny https://github.com/vajkonny, I think we should discuss 
> issues in English s.t. non-native German speakers can follow the 
> discussion.
> 
> Yes, sure.
> I reviewed your changes and saw that you used tabs for indentation. 
> Normally I'm not that strict about that stuff, but in the case of 
> Haskell, indentation really affects the semantic of the code. Even GHC 
> complains about the tabs. So I went ahead and reformatted the tests 
> with 2 spaces per block of indentations.
> Sorry for that. I should have adjusted my editor first.
> 
> Also, I tried to bring the tests into a compiling state, by adding 
> function stubs that are implemented with |undefined|. Can you help me 
> fix the compile errors, than we have an easier job the next time. 
> By doing what? Rendering the stubs into working functions? Then I would 
> need some help from your side. I already implemented genuuid. I think I 
> can do some work on pp with your help, but all the other functions are 
> way too complicated for me to tackle alone. :-/

E.g. how would I access a single element (e.g. GL) from an ILB?

## 

"If you have a choice of two things and can't decide, take both." -- Gregory Corso
